version: '3.8'
services:
  mysql:
    image: "mysql:8.0"
    container_name: etrace_mysql
    command: "mysqld --default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - ./temp/mysql:/var/lib/mysql
    restart: always
    networks:
      - backend
#
networks:
  backend:
    driver: bridge
