version: '3.8'
services:

  #  proemtheus:
  #    image: "prom/prometheus:v2.20.1"
  #    ports:
  #      - 9090:9090
  #    networks:
  #      - backend

  proemtheus:
    image: "bitnami/prometheus"
    ports:
      - 9090:9090
    volumes:
      - ./conf/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    networks:
      - backend

  pushgateway:
    image: "prom/pushgateway"
    ports:
      - 9091:9091
    networks:
      - backend

  grafana:
    image: "grafana/grafana"
    ports:
      - 3000:3000
    networks:
      - backend

networks:
  backend:
    driver: bridge
