version: "3.8"

services:

  collector:
    build:
      context: ./etrace-collector
      dockerfile: Dockerfile
    image: etrace-collector:local
    container_name: etrace_collector
    ports:
      - 2890:2890
    networks:
      - backend

  consumer:
    build:
      context: ./etrace-consumer
      dockerfile: Dockerfile
    image: etrace-consumer:local
    container_name: etrace_consumer
    ports:
      - 8082:8082
    networks:
      - backend

  api:
    build:
      context: ./etrace-api
      dockerfile: Dockerfile
    image: etrace-api:local
    container_name: etrace_api
    ports:
      - 8080:8080
    networks:
      - backend

  stream:
    build:
      context: ./etrace-stream/stream-container
      dockerfile: Dockerfile
    image: etrace-api:local
    container_name: etrace_stream
#    ports:
#      - 9000:9001
    networks:
      - backend

  etrace-prometheus-pushgateway:
    build:
      context: ./etrace-plugins/etrace-prometheus-pushgateway
      dockerfile: Dockerfile
    image: etrace-prometheus-pushgateway:local
    container_name: etrace-prometheus-pushgateway-pushgateway
    ports:
      - 19091:19091
    networks:
      - backend
networks:
  backend:
    driver: bridge