// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/v2/resource.proto

package io.etrace.proto.common.v2;

public interface ResourceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.etrace.proto.common.v2.Resource)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string version = 1;</code>
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 1;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string app_id = 2;</code>
   */
  java.lang.String getAppId();
  /**
   * <code>string app_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getAppIdBytes();

  /**
   * <code>string host_ip = 3;</code>
   */
  java.lang.String getHostIp();
  /**
   * <code>string host_ip = 3;</code>
   */
  com.google.protobuf.ByteString
      getHostIpBytes();

  /**
   * <code>string host_name = 4;</code>
   */
  java.lang.String getHostName();
  /**
   * <code>string host_name = 4;</code>
   */
  com.google.protobuf.ByteString
      getHostNameBytes();

  /**
   * <code>string instance = 5;</code>
   */
  java.lang.String getInstance();
  /**
   * <code>string instance = 5;</code>
   */
  com.google.protobuf.ByteString
      getInstanceBytes();

  /**
   * <code>uint64 ast = 6;</code>
   */
  long getAst();

  /**
   * <code>uint64 crt = 7;</code>
   */
  long getCrt();

  /**
   * <code>uint64 cst = 8;</code>
   */
  long getCst();

  /**
   * <code>uint64 csrt = 9;</code>
   */
  long getCsrt();
}
