// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/v2/resource.proto

package io.etrace.proto.common.v2;

public final class ResourceProto {
  private ResourceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_etrace_proto_common_v2_Resource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_etrace_proto_common_v2_Resource_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030common/v2/resource.proto\022\031io.etrace.pr" +
      "oto.common.v2\"\226\001\n\010Resource\022\017\n\007version\030\001 " +
      "\001(\t\022\016\n\006app_id\030\002 \001(\t\022\017\n\007host_ip\030\003 \001(\t\022\021\n\t" +
      "host_name\030\004 \001(\t\022\020\n\010instance\030\005 \001(\t\022\013\n\003ast" +
      "\030\006 \001(\004\022\013\n\003crt\030\007 \001(\004\022\013\n\003cst\030\010 \001(\004\022\014\n\004csrt" +
      "\030\t \001(\004B,\n\031io.etrace.proto.common.v2B\rRes" +
      "ourceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_io_etrace_proto_common_v2_Resource_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_etrace_proto_common_v2_Resource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_etrace_proto_common_v2_Resource_descriptor,
        new java.lang.String[] { "Version", "AppId", "HostIp", "HostName", "Instance", "Ast", "Crt", "Cst", "Csrt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
