// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/v2/resource.proto

package io.etrace.proto.common.v2;

/**
 * Protobuf type {@code io.etrace.proto.common.v2.Resource}
 */
public  final class Resource extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.etrace.proto.common.v2.Resource)
    ResourceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Resource.newBuilder() to construct.
  private Resource(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Resource() {
    version_ = "";
    appId_ = "";
    hostIp_ = "";
    hostName_ = "";
    instance_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Resource(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            version_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            appId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            hostIp_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            hostName_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            instance_ = s;
            break;
          }
          case 48: {

            ast_ = input.readUInt64();
            break;
          }
          case 56: {

            crt_ = input.readUInt64();
            break;
          }
          case 64: {

            cst_ = input.readUInt64();
            break;
          }
          case 72: {

            csrt_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.etrace.proto.common.v2.ResourceProto.internal_static_io_etrace_proto_common_v2_Resource_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.etrace.proto.common.v2.ResourceProto.internal_static_io_etrace_proto_common_v2_Resource_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.etrace.proto.common.v2.Resource.class, io.etrace.proto.common.v2.Resource.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private volatile java.lang.Object version_;
  /**
   * <code>string version = 1;</code>
   */
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 1;</code>
   */
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APP_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object appId_;
  /**
   * <code>string app_id = 2;</code>
   */
  public java.lang.String getAppId() {
    java.lang.Object ref = appId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appId_ = s;
      return s;
    }
  }
  /**
   * <code>string app_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAppIdBytes() {
    java.lang.Object ref = appId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HOST_IP_FIELD_NUMBER = 3;
  private volatile java.lang.Object hostIp_;
  /**
   * <code>string host_ip = 3;</code>
   */
  public java.lang.String getHostIp() {
    java.lang.Object ref = hostIp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hostIp_ = s;
      return s;
    }
  }
  /**
   * <code>string host_ip = 3;</code>
   */
  public com.google.protobuf.ByteString
      getHostIpBytes() {
    java.lang.Object ref = hostIp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hostIp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HOST_NAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object hostName_;
  /**
   * <code>string host_name = 4;</code>
   */
  public java.lang.String getHostName() {
    java.lang.Object ref = hostName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hostName_ = s;
      return s;
    }
  }
  /**
   * <code>string host_name = 4;</code>
   */
  public com.google.protobuf.ByteString
      getHostNameBytes() {
    java.lang.Object ref = hostName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hostName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INSTANCE_FIELD_NUMBER = 5;
  private volatile java.lang.Object instance_;
  /**
   * <code>string instance = 5;</code>
   */
  public java.lang.String getInstance() {
    java.lang.Object ref = instance_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      instance_ = s;
      return s;
    }
  }
  /**
   * <code>string instance = 5;</code>
   */
  public com.google.protobuf.ByteString
      getInstanceBytes() {
    java.lang.Object ref = instance_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      instance_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AST_FIELD_NUMBER = 6;
  private long ast_;
  /**
   * <code>uint64 ast = 6;</code>
   */
  public long getAst() {
    return ast_;
  }

  public static final int CRT_FIELD_NUMBER = 7;
  private long crt_;
  /**
   * <code>uint64 crt = 7;</code>
   */
  public long getCrt() {
    return crt_;
  }

  public static final int CST_FIELD_NUMBER = 8;
  private long cst_;
  /**
   * <code>uint64 cst = 8;</code>
   */
  public long getCst() {
    return cst_;
  }

  public static final int CSRT_FIELD_NUMBER = 9;
  private long csrt_;
  /**
   * <code>uint64 csrt = 9;</code>
   */
  public long getCsrt() {
    return csrt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, version_);
    }
    if (!getAppIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, appId_);
    }
    if (!getHostIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, hostIp_);
    }
    if (!getHostNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, hostName_);
    }
    if (!getInstanceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, instance_);
    }
    if (ast_ != 0L) {
      output.writeUInt64(6, ast_);
    }
    if (crt_ != 0L) {
      output.writeUInt64(7, crt_);
    }
    if (cst_ != 0L) {
      output.writeUInt64(8, cst_);
    }
    if (csrt_ != 0L) {
      output.writeUInt64(9, csrt_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, version_);
    }
    if (!getAppIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, appId_);
    }
    if (!getHostIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, hostIp_);
    }
    if (!getHostNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, hostName_);
    }
    if (!getInstanceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, instance_);
    }
    if (ast_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, ast_);
    }
    if (crt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, crt_);
    }
    if (cst_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(8, cst_);
    }
    if (csrt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, csrt_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.etrace.proto.common.v2.Resource)) {
      return super.equals(obj);
    }
    io.etrace.proto.common.v2.Resource other = (io.etrace.proto.common.v2.Resource) obj;

    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (!getAppId()
        .equals(other.getAppId())) return false;
    if (!getHostIp()
        .equals(other.getHostIp())) return false;
    if (!getHostName()
        .equals(other.getHostName())) return false;
    if (!getInstance()
        .equals(other.getInstance())) return false;
    if (getAst()
        != other.getAst()) return false;
    if (getCrt()
        != other.getCrt()) return false;
    if (getCst()
        != other.getCst()) return false;
    if (getCsrt()
        != other.getCsrt()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    hash = (37 * hash) + APP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAppId().hashCode();
    hash = (37 * hash) + HOST_IP_FIELD_NUMBER;
    hash = (53 * hash) + getHostIp().hashCode();
    hash = (37 * hash) + HOST_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getHostName().hashCode();
    hash = (37 * hash) + INSTANCE_FIELD_NUMBER;
    hash = (53 * hash) + getInstance().hashCode();
    hash = (37 * hash) + AST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAst());
    hash = (37 * hash) + CRT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCrt());
    hash = (37 * hash) + CST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCst());
    hash = (37 * hash) + CSRT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCsrt());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.etrace.proto.common.v2.Resource parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etrace.proto.common.v2.Resource parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etrace.proto.common.v2.Resource parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etrace.proto.common.v2.Resource parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etrace.proto.common.v2.Resource parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etrace.proto.common.v2.Resource parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etrace.proto.common.v2.Resource parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.etrace.proto.common.v2.Resource parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.etrace.proto.common.v2.Resource parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.etrace.proto.common.v2.Resource parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.etrace.proto.common.v2.Resource parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.etrace.proto.common.v2.Resource parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.etrace.proto.common.v2.Resource prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.etrace.proto.common.v2.Resource}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.etrace.proto.common.v2.Resource)
      io.etrace.proto.common.v2.ResourceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.etrace.proto.common.v2.ResourceProto.internal_static_io_etrace_proto_common_v2_Resource_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.etrace.proto.common.v2.ResourceProto.internal_static_io_etrace_proto_common_v2_Resource_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.etrace.proto.common.v2.Resource.class, io.etrace.proto.common.v2.Resource.Builder.class);
    }

    // Construct using io.etrace.proto.common.v2.Resource.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = "";

      appId_ = "";

      hostIp_ = "";

      hostName_ = "";

      instance_ = "";

      ast_ = 0L;

      crt_ = 0L;

      cst_ = 0L;

      csrt_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.etrace.proto.common.v2.ResourceProto.internal_static_io_etrace_proto_common_v2_Resource_descriptor;
    }

    @java.lang.Override
    public io.etrace.proto.common.v2.Resource getDefaultInstanceForType() {
      return io.etrace.proto.common.v2.Resource.getDefaultInstance();
    }

    @java.lang.Override
    public io.etrace.proto.common.v2.Resource build() {
      io.etrace.proto.common.v2.Resource result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.etrace.proto.common.v2.Resource buildPartial() {
      io.etrace.proto.common.v2.Resource result = new io.etrace.proto.common.v2.Resource(this);
      result.version_ = version_;
      result.appId_ = appId_;
      result.hostIp_ = hostIp_;
      result.hostName_ = hostName_;
      result.instance_ = instance_;
      result.ast_ = ast_;
      result.crt_ = crt_;
      result.cst_ = cst_;
      result.csrt_ = csrt_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.etrace.proto.common.v2.Resource) {
        return mergeFrom((io.etrace.proto.common.v2.Resource)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.etrace.proto.common.v2.Resource other) {
      if (other == io.etrace.proto.common.v2.Resource.getDefaultInstance()) return this;
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        onChanged();
      }
      if (!other.getAppId().isEmpty()) {
        appId_ = other.appId_;
        onChanged();
      }
      if (!other.getHostIp().isEmpty()) {
        hostIp_ = other.hostIp_;
        onChanged();
      }
      if (!other.getHostName().isEmpty()) {
        hostName_ = other.hostName_;
        onChanged();
      }
      if (!other.getInstance().isEmpty()) {
        instance_ = other.instance_;
        onChanged();
      }
      if (other.getAst() != 0L) {
        setAst(other.getAst());
      }
      if (other.getCrt() != 0L) {
        setCrt(other.getCrt());
      }
      if (other.getCst() != 0L) {
        setCst(other.getCst());
      }
      if (other.getCsrt() != 0L) {
        setCsrt(other.getCsrt());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.etrace.proto.common.v2.Resource parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.etrace.proto.common.v2.Resource) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <code>string version = 1;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string version = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 1;</code>
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 1;</code>
     */
    public Builder clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <code>string version = 1;</code>
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      version_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object appId_ = "";
    /**
     * <code>string app_id = 2;</code>
     */
    public java.lang.String getAppId() {
      java.lang.Object ref = appId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string app_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string app_id = 2;</code>
     */
    public Builder setAppId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      appId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string app_id = 2;</code>
     */
    public Builder clearAppId() {
      
      appId_ = getDefaultInstance().getAppId();
      onChanged();
      return this;
    }
    /**
     * <code>string app_id = 2;</code>
     */
    public Builder setAppIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      appId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object hostIp_ = "";
    /**
     * <code>string host_ip = 3;</code>
     */
    public java.lang.String getHostIp() {
      java.lang.Object ref = hostIp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostIp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string host_ip = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHostIpBytes() {
      java.lang.Object ref = hostIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string host_ip = 3;</code>
     */
    public Builder setHostIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hostIp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string host_ip = 3;</code>
     */
    public Builder clearHostIp() {
      
      hostIp_ = getDefaultInstance().getHostIp();
      onChanged();
      return this;
    }
    /**
     * <code>string host_ip = 3;</code>
     */
    public Builder setHostIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hostIp_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object hostName_ = "";
    /**
     * <code>string host_name = 4;</code>
     */
    public java.lang.String getHostName() {
      java.lang.Object ref = hostName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string host_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getHostNameBytes() {
      java.lang.Object ref = hostName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string host_name = 4;</code>
     */
    public Builder setHostName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hostName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string host_name = 4;</code>
     */
    public Builder clearHostName() {
      
      hostName_ = getDefaultInstance().getHostName();
      onChanged();
      return this;
    }
    /**
     * <code>string host_name = 4;</code>
     */
    public Builder setHostNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hostName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object instance_ = "";
    /**
     * <code>string instance = 5;</code>
     */
    public java.lang.String getInstance() {
      java.lang.Object ref = instance_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instance_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string instance = 5;</code>
     */
    public com.google.protobuf.ByteString
        getInstanceBytes() {
      java.lang.Object ref = instance_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string instance = 5;</code>
     */
    public Builder setInstance(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      instance_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string instance = 5;</code>
     */
    public Builder clearInstance() {
      
      instance_ = getDefaultInstance().getInstance();
      onChanged();
      return this;
    }
    /**
     * <code>string instance = 5;</code>
     */
    public Builder setInstanceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      instance_ = value;
      onChanged();
      return this;
    }

    private long ast_ ;
    /**
     * <code>uint64 ast = 6;</code>
     */
    public long getAst() {
      return ast_;
    }
    /**
     * <code>uint64 ast = 6;</code>
     */
    public Builder setAst(long value) {
      
      ast_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 ast = 6;</code>
     */
    public Builder clearAst() {
      
      ast_ = 0L;
      onChanged();
      return this;
    }

    private long crt_ ;
    /**
     * <code>uint64 crt = 7;</code>
     */
    public long getCrt() {
      return crt_;
    }
    /**
     * <code>uint64 crt = 7;</code>
     */
    public Builder setCrt(long value) {
      
      crt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 crt = 7;</code>
     */
    public Builder clearCrt() {
      
      crt_ = 0L;
      onChanged();
      return this;
    }

    private long cst_ ;
    /**
     * <code>uint64 cst = 8;</code>
     */
    public long getCst() {
      return cst_;
    }
    /**
     * <code>uint64 cst = 8;</code>
     */
    public Builder setCst(long value) {
      
      cst_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 cst = 8;</code>
     */
    public Builder clearCst() {
      
      cst_ = 0L;
      onChanged();
      return this;
    }

    private long csrt_ ;
    /**
     * <code>uint64 csrt = 9;</code>
     */
    public long getCsrt() {
      return csrt_;
    }
    /**
     * <code>uint64 csrt = 9;</code>
     */
    public Builder setCsrt(long value) {
      
      csrt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 csrt = 9;</code>
     */
    public Builder clearCsrt() {
      
      csrt_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.etrace.proto.common.v2.Resource)
  }

  // @@protoc_insertion_point(class_scope:io.etrace.proto.common.v2.Resource)
  private static final io.etrace.proto.common.v2.Resource DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.etrace.proto.common.v2.Resource();
  }

  public static io.etrace.proto.common.v2.Resource getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Resource>
      PARSER = new com.google.protobuf.AbstractParser<Resource>() {
    @java.lang.Override
    public Resource parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Resource(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Resource> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Resource> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.etrace.proto.common.v2.Resource getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

