// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector/trace/v2/trace_service.proto

package io.etrace.proto.collector.trace.v2;

public interface TraceServiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.etrace.proto.collector.trace.v2.TraceServiceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes result = 1;</code>
   */
  com.google.protobuf.ByteString getResult();
}
