// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector/trace/v2/trace_service.proto

package io.etrace.proto.collector.trace.v2;

public final class TraceServiceProto {
  private TraceServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_etrace_proto_collector_trace_v2_TraceServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_etrace_proto_collector_trace_v2_TraceServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_etrace_proto_collector_trace_v2_TraceServiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_etrace_proto_collector_trace_v2_TraceServiceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&collector/trace/v2/trace_service.proto" +
      "\022\"io.etrace.proto.collector.trace.v2\032\024tr" +
      "ace/v2/trace.proto\032\030common/v2/resource.p" +
      "roto\"|\n\023TraceServiceRequest\0225\n\010resource\030" +
      "\001 \001(\0132#.io.etrace.proto.common.v2.Resour" +
      "ce\022.\n\005trace\030\002 \003(\0132\037.io.etrace.proto.trac" +
      "e.v2.Trace\"&\n\024TraceServiceResponse\022\016\n\006re" +
      "sult\030\001 \001(\0142\213\001\n\014TraceService\022{\n\004Send\0227.io" +
      ".etrace.proto.collector.trace.v2.TraceSe" +
      "rviceRequest\0328.io.etrace.proto.collector" +
      ".trace.v2.TraceServiceResponse\"\000B9\n\"io.e" +
      "trace.proto.collector.trace.v2B\021TraceSer" +
      "viceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.etrace.proto.trace.v2.TraceProto.getDescriptor(),
          io.etrace.proto.common.v2.ResourceProto.getDescriptor(),
        }, assigner);
    internal_static_io_etrace_proto_collector_trace_v2_TraceServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_etrace_proto_collector_trace_v2_TraceServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_etrace_proto_collector_trace_v2_TraceServiceRequest_descriptor,
        new java.lang.String[] { "Resource", "Trace", });
    internal_static_io_etrace_proto_collector_trace_v2_TraceServiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_etrace_proto_collector_trace_v2_TraceServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_etrace_proto_collector_trace_v2_TraceServiceResponse_descriptor,
        new java.lang.String[] { "Result", });
    io.etrace.proto.trace.v2.TraceProto.getDescriptor();
    io.etrace.proto.common.v2.ResourceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
