// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector/trace/v2/trace_service.proto

package io.etrace.proto.collector.trace.v2;

public interface TraceServiceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.etrace.proto.collector.trace.v2.TraceServiceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.etrace.proto.common.v2.Resource resource = 1;</code>
   */
  boolean hasResource();
  /**
   * <code>.io.etrace.proto.common.v2.Resource resource = 1;</code>
   */
  io.etrace.proto.common.v2.Resource getResource();
  /**
   * <code>.io.etrace.proto.common.v2.Resource resource = 1;</code>
   */
  io.etrace.proto.common.v2.ResourceOrBuilder getResourceOrBuilder();

  /**
   * <code>repeated .io.etrace.proto.trace.v2.Trace trace = 2;</code>
   */
  java.util.List<io.etrace.proto.trace.v2.Trace> 
      getTraceList();
  /**
   * <code>repeated .io.etrace.proto.trace.v2.Trace trace = 2;</code>
   */
  io.etrace.proto.trace.v2.Trace getTrace(int index);
  /**
   * <code>repeated .io.etrace.proto.trace.v2.Trace trace = 2;</code>
   */
  int getTraceCount();
  /**
   * <code>repeated .io.etrace.proto.trace.v2.Trace trace = 2;</code>
   */
  java.util.List<? extends io.etrace.proto.trace.v2.TraceOrBuilder> 
      getTraceOrBuilderList();
  /**
   * <code>repeated .io.etrace.proto.trace.v2.Trace trace = 2;</code>
   */
  io.etrace.proto.trace.v2.TraceOrBuilder getTraceOrBuilder(
      int index);
}
