# spring-web
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

etrace:
  appId: "etrace.consumer"
  backendAddress: "collector:2890"
  consumer:
    keeper: 7
    hbase:
      - tableName: stack
        regionSize: 720
    hdfs:
      path: hdfs://mycluster/etrace

    resources:
      - name: kafka_trace
        type: KAFKA
        props:
          zookeeper.connect: zookeeper:2181

logging:
  level:
    root: INFO