# spring-web
server:
  port: 8082
  connection-timeout: 10000
  tomcat:
    accept-count: 256
    max-threads: 16
    min-spare-threads: 4

consumer:
  keeper: 7
  hbase:
    - tableName: stack
      regionSize: 720
  hdfs:
    path: hdfs://mycluster/etrace

  resources:
    - name: kafka_trace
      type: KAFKA
      props:
        zookeeper.connect: zookeeper:2181

etrace:
  appId: "etrace.consumer"
  backendAddress: "collector:2890"

logging:
  level:
    root: INFO