// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics/v2/metrics.proto

package io.etrace.proto.metrics.v2;

/**
 * Protobuf enum {@code io.etrace.proto.metrics.v2.AggregateType}
 */
public enum AggregateType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SUM = 0;</code>
   */
  SUM(0),
  /**
   * <code>GAUGE = 1;</code>
   */
  GAUGE(1),
  /**
   * <code>MAX = 2;</code>
   */
  MAX(2),
  /**
   * <code>MIN = 3;</code>
   */
  MIN(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SUM = 0;</code>
   */
  public static final int SUM_VALUE = 0;
  /**
   * <code>GAUGE = 1;</code>
   */
  public static final int GAUGE_VALUE = 1;
  /**
   * <code>MAX = 2;</code>
   */
  public static final int MAX_VALUE = 2;
  /**
   * <code>MIN = 3;</code>
   */
  public static final int MIN_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AggregateType valueOf(int value) {
    return forNumber(value);
  }

  public static AggregateType forNumber(int value) {
    switch (value) {
      case 0: return SUM;
      case 1: return GAUGE;
      case 2: return MAX;
      case 3: return MIN;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AggregateType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AggregateType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AggregateType>() {
          public AggregateType findValueByNumber(int number) {
            return AggregateType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.etrace.proto.metrics.v2.MetricsProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final AggregateType[] VALUES = values();

  public static AggregateType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AggregateType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:io.etrace.proto.metrics.v2.AggregateType)
}

