// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics/v2/metrics.proto

package io.etrace.proto.metrics.v2;

/**
 * Protobuf type {@code io.etrace.proto.metrics.v2.Bucket}
 */
public  final class Bucket extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.etrace.proto.metrics.v2.Bucket)
    BucketOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Bucket.newBuilder() to construct.
  private Bucket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Bucket() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Bucket(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            bucket_ = input.readDouble();
            break;
          }
          case 17: {

            count_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_Bucket_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_Bucket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.etrace.proto.metrics.v2.Bucket.class, io.etrace.proto.metrics.v2.Bucket.Builder.class);
  }

  public static final int BUCKET_FIELD_NUMBER = 1;
  private double bucket_;
  /**
   * <code>double bucket = 1;</code>
   */
  public double getBucket() {
    return bucket_;
  }

  public static final int COUNT_FIELD_NUMBER = 2;
  private double count_;
  /**
   * <code>double count = 2;</code>
   */
  public double getCount() {
    return count_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (bucket_ != 0D) {
      output.writeDouble(1, bucket_);
    }
    if (count_ != 0D) {
      output.writeDouble(2, count_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (bucket_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, bucket_);
    }
    if (count_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, count_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.etrace.proto.metrics.v2.Bucket)) {
      return super.equals(obj);
    }
    io.etrace.proto.metrics.v2.Bucket other = (io.etrace.proto.metrics.v2.Bucket) obj;

    if (java.lang.Double.doubleToLongBits(getBucket())
        != java.lang.Double.doubleToLongBits(
            other.getBucket())) return false;
    if (java.lang.Double.doubleToLongBits(getCount())
        != java.lang.Double.doubleToLongBits(
            other.getCount())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BUCKET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBucket()));
    hash = (37 * hash) + COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCount()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.etrace.proto.metrics.v2.Bucket parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etrace.proto.metrics.v2.Bucket parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etrace.proto.metrics.v2.Bucket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etrace.proto.metrics.v2.Bucket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etrace.proto.metrics.v2.Bucket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etrace.proto.metrics.v2.Bucket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etrace.proto.metrics.v2.Bucket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.etrace.proto.metrics.v2.Bucket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.etrace.proto.metrics.v2.Bucket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.etrace.proto.metrics.v2.Bucket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.etrace.proto.metrics.v2.Bucket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.etrace.proto.metrics.v2.Bucket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.etrace.proto.metrics.v2.Bucket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.etrace.proto.metrics.v2.Bucket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.etrace.proto.metrics.v2.Bucket)
      io.etrace.proto.metrics.v2.BucketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_Bucket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_Bucket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.etrace.proto.metrics.v2.Bucket.class, io.etrace.proto.metrics.v2.Bucket.Builder.class);
    }

    // Construct using io.etrace.proto.metrics.v2.Bucket.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bucket_ = 0D;

      count_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_Bucket_descriptor;
    }

    @java.lang.Override
    public io.etrace.proto.metrics.v2.Bucket getDefaultInstanceForType() {
      return io.etrace.proto.metrics.v2.Bucket.getDefaultInstance();
    }

    @java.lang.Override
    public io.etrace.proto.metrics.v2.Bucket build() {
      io.etrace.proto.metrics.v2.Bucket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.etrace.proto.metrics.v2.Bucket buildPartial() {
      io.etrace.proto.metrics.v2.Bucket result = new io.etrace.proto.metrics.v2.Bucket(this);
      result.bucket_ = bucket_;
      result.count_ = count_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.etrace.proto.metrics.v2.Bucket) {
        return mergeFrom((io.etrace.proto.metrics.v2.Bucket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.etrace.proto.metrics.v2.Bucket other) {
      if (other == io.etrace.proto.metrics.v2.Bucket.getDefaultInstance()) return this;
      if (other.getBucket() != 0D) {
        setBucket(other.getBucket());
      }
      if (other.getCount() != 0D) {
        setCount(other.getCount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.etrace.proto.metrics.v2.Bucket parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.etrace.proto.metrics.v2.Bucket) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double bucket_ ;
    /**
     * <code>double bucket = 1;</code>
     */
    public double getBucket() {
      return bucket_;
    }
    /**
     * <code>double bucket = 1;</code>
     */
    public Builder setBucket(double value) {
      
      bucket_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double bucket = 1;</code>
     */
    public Builder clearBucket() {
      
      bucket_ = 0D;
      onChanged();
      return this;
    }

    private double count_ ;
    /**
     * <code>double count = 2;</code>
     */
    public double getCount() {
      return count_;
    }
    /**
     * <code>double count = 2;</code>
     */
    public Builder setCount(double value) {
      
      count_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double count = 2;</code>
     */
    public Builder clearCount() {
      
      count_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.etrace.proto.metrics.v2.Bucket)
  }

  // @@protoc_insertion_point(class_scope:io.etrace.proto.metrics.v2.Bucket)
  private static final io.etrace.proto.metrics.v2.Bucket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.etrace.proto.metrics.v2.Bucket();
  }

  public static io.etrace.proto.metrics.v2.Bucket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Bucket>
      PARSER = new com.google.protobuf.AbstractParser<Bucket>() {
    @java.lang.Override
    public Bucket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Bucket(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Bucket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Bucket> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.etrace.proto.metrics.v2.Bucket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

