// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics/v2/metrics.proto

package io.etrace.proto.metrics.v2;

public interface BucketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.etrace.proto.metrics.v2.Bucket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double bucket = 1;</code>
   */
  double getBucket();

  /**
   * <code>double count = 2;</code>
   */
  double getCount();
}
