// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics/v2/metrics.proto

package io.etrace.proto.metrics.v2;

/**
 * Protobuf type {@code io.etrace.proto.metrics.v2.Field}
 */
public  final class Field extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.etrace.proto.metrics.v2.Field)
    FieldOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Field.newBuilder() to construct.
  private Field(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Field() {
    aggregateType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Field(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            aggregateType_ = rawValue;
            break;
          }
          case 800: {
            valueCase_ = 100;
            value_ = input.readUInt64();
            break;
          }
          case 809: {
            valueCase_ = 101;
            value_ = input.readDouble();
            break;
          }
          case 818: {
            java.lang.String s = input.readStringRequireUtf8();
            valueCase_ = 102;
            value_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_Field_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_Field_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.etrace.proto.metrics.v2.Field.class, io.etrace.proto.metrics.v2.Field.Builder.class);
  }

  private int valueCase_ = 0;
  private java.lang.Object value_;
  public enum ValueCase
      implements com.google.protobuf.Internal.EnumLite {
    LONGVAL(100),
    DOUBLEVAL(101),
    STRINGVAL(102),
    VALUE_NOT_SET(0);
    private final int value;
    private ValueCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValueCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValueCase forNumber(int value) {
      switch (value) {
        case 100: return LONGVAL;
        case 101: return DOUBLEVAL;
        case 102: return STRINGVAL;
        case 0: return VALUE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ValueCase
  getValueCase() {
    return ValueCase.forNumber(
        valueCase_);
  }

  public static final int AGGREGATETYPE_FIELD_NUMBER = 1;
  private int aggregateType_;
  /**
   * <code>.io.etrace.proto.metrics.v2.AggregateType aggregateType = 1;</code>
   */
  public int getAggregateTypeValue() {
    return aggregateType_;
  }
  /**
   * <code>.io.etrace.proto.metrics.v2.AggregateType aggregateType = 1;</code>
   */
  public io.etrace.proto.metrics.v2.AggregateType getAggregateType() {
    @SuppressWarnings("deprecation")
    io.etrace.proto.metrics.v2.AggregateType result = io.etrace.proto.metrics.v2.AggregateType.valueOf(aggregateType_);
    return result == null ? io.etrace.proto.metrics.v2.AggregateType.UNRECOGNIZED : result;
  }

  public static final int LONGVAL_FIELD_NUMBER = 100;
  /**
   * <code>uint64 longVal = 100;</code>
   */
  public long getLongVal() {
    if (valueCase_ == 100) {
      return (java.lang.Long) value_;
    }
    return 0L;
  }

  public static final int DOUBLEVAL_FIELD_NUMBER = 101;
  /**
   * <code>double doubleVal = 101;</code>
   */
  public double getDoubleVal() {
    if (valueCase_ == 101) {
      return (java.lang.Double) value_;
    }
    return 0D;
  }

  public static final int STRINGVAL_FIELD_NUMBER = 102;
  /**
   * <code>string stringVal = 102;</code>
   */
  public java.lang.String getStringVal() {
    java.lang.Object ref = "";
    if (valueCase_ == 102) {
      ref = value_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (valueCase_ == 102) {
        value_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string stringVal = 102;</code>
   */
  public com.google.protobuf.ByteString
      getStringValBytes() {
    java.lang.Object ref = "";
    if (valueCase_ == 102) {
      ref = value_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (valueCase_ == 102) {
        value_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (aggregateType_ != io.etrace.proto.metrics.v2.AggregateType.SUM.getNumber()) {
      output.writeEnum(1, aggregateType_);
    }
    if (valueCase_ == 100) {
      output.writeUInt64(
          100, (long)((java.lang.Long) value_));
    }
    if (valueCase_ == 101) {
      output.writeDouble(
          101, (double)((java.lang.Double) value_));
    }
    if (valueCase_ == 102) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 102, value_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (aggregateType_ != io.etrace.proto.metrics.v2.AggregateType.SUM.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, aggregateType_);
    }
    if (valueCase_ == 100) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(
            100, (long)((java.lang.Long) value_));
    }
    if (valueCase_ == 101) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(
            101, (double)((java.lang.Double) value_));
    }
    if (valueCase_ == 102) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(102, value_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.etrace.proto.metrics.v2.Field)) {
      return super.equals(obj);
    }
    io.etrace.proto.metrics.v2.Field other = (io.etrace.proto.metrics.v2.Field) obj;

    if (aggregateType_ != other.aggregateType_) return false;
    if (!getValueCase().equals(other.getValueCase())) return false;
    switch (valueCase_) {
      case 100:
        if (getLongVal()
            != other.getLongVal()) return false;
        break;
      case 101:
        if (java.lang.Double.doubleToLongBits(getDoubleVal())
            != java.lang.Double.doubleToLongBits(
                other.getDoubleVal())) return false;
        break;
      case 102:
        if (!getStringVal()
            .equals(other.getStringVal())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AGGREGATETYPE_FIELD_NUMBER;
    hash = (53 * hash) + aggregateType_;
    switch (valueCase_) {
      case 100:
        hash = (37 * hash) + LONGVAL_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLongVal());
        break;
      case 101:
        hash = (37 * hash) + DOUBLEVAL_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getDoubleVal()));
        break;
      case 102:
        hash = (37 * hash) + STRINGVAL_FIELD_NUMBER;
        hash = (53 * hash) + getStringVal().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.etrace.proto.metrics.v2.Field parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etrace.proto.metrics.v2.Field parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etrace.proto.metrics.v2.Field parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etrace.proto.metrics.v2.Field parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etrace.proto.metrics.v2.Field parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etrace.proto.metrics.v2.Field parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etrace.proto.metrics.v2.Field parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.etrace.proto.metrics.v2.Field parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.etrace.proto.metrics.v2.Field parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.etrace.proto.metrics.v2.Field parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.etrace.proto.metrics.v2.Field parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.etrace.proto.metrics.v2.Field parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.etrace.proto.metrics.v2.Field prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.etrace.proto.metrics.v2.Field}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.etrace.proto.metrics.v2.Field)
      io.etrace.proto.metrics.v2.FieldOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_Field_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_Field_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.etrace.proto.metrics.v2.Field.class, io.etrace.proto.metrics.v2.Field.Builder.class);
    }

    // Construct using io.etrace.proto.metrics.v2.Field.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      aggregateType_ = 0;

      valueCase_ = 0;
      value_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_Field_descriptor;
    }

    @java.lang.Override
    public io.etrace.proto.metrics.v2.Field getDefaultInstanceForType() {
      return io.etrace.proto.metrics.v2.Field.getDefaultInstance();
    }

    @java.lang.Override
    public io.etrace.proto.metrics.v2.Field build() {
      io.etrace.proto.metrics.v2.Field result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.etrace.proto.metrics.v2.Field buildPartial() {
      io.etrace.proto.metrics.v2.Field result = new io.etrace.proto.metrics.v2.Field(this);
      result.aggregateType_ = aggregateType_;
      if (valueCase_ == 100) {
        result.value_ = value_;
      }
      if (valueCase_ == 101) {
        result.value_ = value_;
      }
      if (valueCase_ == 102) {
        result.value_ = value_;
      }
      result.valueCase_ = valueCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.etrace.proto.metrics.v2.Field) {
        return mergeFrom((io.etrace.proto.metrics.v2.Field)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.etrace.proto.metrics.v2.Field other) {
      if (other == io.etrace.proto.metrics.v2.Field.getDefaultInstance()) return this;
      if (other.aggregateType_ != 0) {
        setAggregateTypeValue(other.getAggregateTypeValue());
      }
      switch (other.getValueCase()) {
        case LONGVAL: {
          setLongVal(other.getLongVal());
          break;
        }
        case DOUBLEVAL: {
          setDoubleVal(other.getDoubleVal());
          break;
        }
        case STRINGVAL: {
          valueCase_ = 102;
          value_ = other.value_;
          onChanged();
          break;
        }
        case VALUE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.etrace.proto.metrics.v2.Field parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.etrace.proto.metrics.v2.Field) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int valueCase_ = 0;
    private java.lang.Object value_;
    public ValueCase
        getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public Builder clearValue() {
      valueCase_ = 0;
      value_ = null;
      onChanged();
      return this;
    }


    private int aggregateType_ = 0;
    /**
     * <code>.io.etrace.proto.metrics.v2.AggregateType aggregateType = 1;</code>
     */
    public int getAggregateTypeValue() {
      return aggregateType_;
    }
    /**
     * <code>.io.etrace.proto.metrics.v2.AggregateType aggregateType = 1;</code>
     */
    public Builder setAggregateTypeValue(int value) {
      aggregateType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.io.etrace.proto.metrics.v2.AggregateType aggregateType = 1;</code>
     */
    public io.etrace.proto.metrics.v2.AggregateType getAggregateType() {
      @SuppressWarnings("deprecation")
      io.etrace.proto.metrics.v2.AggregateType result = io.etrace.proto.metrics.v2.AggregateType.valueOf(aggregateType_);
      return result == null ? io.etrace.proto.metrics.v2.AggregateType.UNRECOGNIZED : result;
    }
    /**
     * <code>.io.etrace.proto.metrics.v2.AggregateType aggregateType = 1;</code>
     */
    public Builder setAggregateType(io.etrace.proto.metrics.v2.AggregateType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      aggregateType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.io.etrace.proto.metrics.v2.AggregateType aggregateType = 1;</code>
     */
    public Builder clearAggregateType() {
      
      aggregateType_ = 0;
      onChanged();
      return this;
    }

    /**
     * <code>uint64 longVal = 100;</code>
     */
    public long getLongVal() {
      if (valueCase_ == 100) {
        return (java.lang.Long) value_;
      }
      return 0L;
    }
    /**
     * <code>uint64 longVal = 100;</code>
     */
    public Builder setLongVal(long value) {
      valueCase_ = 100;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 longVal = 100;</code>
     */
    public Builder clearLongVal() {
      if (valueCase_ == 100) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>double doubleVal = 101;</code>
     */
    public double getDoubleVal() {
      if (valueCase_ == 101) {
        return (java.lang.Double) value_;
      }
      return 0D;
    }
    /**
     * <code>double doubleVal = 101;</code>
     */
    public Builder setDoubleVal(double value) {
      valueCase_ = 101;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double doubleVal = 101;</code>
     */
    public Builder clearDoubleVal() {
      if (valueCase_ == 101) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>string stringVal = 102;</code>
     */
    public java.lang.String getStringVal() {
      java.lang.Object ref = "";
      if (valueCase_ == 102) {
        ref = value_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (valueCase_ == 102) {
          value_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stringVal = 102;</code>
     */
    public com.google.protobuf.ByteString
        getStringValBytes() {
      java.lang.Object ref = "";
      if (valueCase_ == 102) {
        ref = value_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valueCase_ == 102) {
          value_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stringVal = 102;</code>
     */
    public Builder setStringVal(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 102;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string stringVal = 102;</code>
     */
    public Builder clearStringVal() {
      if (valueCase_ == 102) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string stringVal = 102;</code>
     */
    public Builder setStringValBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      valueCase_ = 102;
      value_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.etrace.proto.metrics.v2.Field)
  }

  // @@protoc_insertion_point(class_scope:io.etrace.proto.metrics.v2.Field)
  private static final io.etrace.proto.metrics.v2.Field DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.etrace.proto.metrics.v2.Field();
  }

  public static io.etrace.proto.metrics.v2.Field getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Field>
      PARSER = new com.google.protobuf.AbstractParser<Field>() {
    @java.lang.Override
    public Field parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Field(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Field> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Field> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.etrace.proto.metrics.v2.Field getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

