// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics/v2/metrics.proto

package io.etrace.proto.metrics.v2;

public interface FieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.etrace.proto.metrics.v2.Field)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.etrace.proto.metrics.v2.AggregateType aggregateType = 1;</code>
   */
  int getAggregateTypeValue();
  /**
   * <code>.io.etrace.proto.metrics.v2.AggregateType aggregateType = 1;</code>
   */
  io.etrace.proto.metrics.v2.AggregateType getAggregateType();

  /**
   * <code>uint64 longVal = 100;</code>
   */
  long getLongVal();

  /**
   * <code>double doubleVal = 101;</code>
   */
  double getDoubleVal();

  /**
   * <code>string stringVal = 102;</code>
   */
  java.lang.String getStringVal();
  /**
   * <code>string stringVal = 102;</code>
   */
  com.google.protobuf.ByteString
      getStringValBytes();

  public io.etrace.proto.metrics.v2.Field.ValueCase getValueCase();
}
