// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics/v2/metrics.proto

package io.etrace.proto.metrics.v2;

/**
 * Protobuf type {@code io.etrace.proto.metrics.v2.Metric}
 */
public  final class Metric extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.etrace.proto.metrics.v2.Metric)
    MetricOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Metric.newBuilder() to construct.
  private Metric(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Metric() {
    kind_ = 0;
    name_ = "";
    buckets_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Metric(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            kind_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {

            timestamp_ = input.readUInt64();
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              tags_ = com.google.protobuf.MapField.newMapField(
                  TagsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000008;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            tags__ = input.readMessage(
                TagsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            tags_.getMutableMap().put(
                tags__.getKey(), tags__.getValue());
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) != 0)) {
              fields_ = com.google.protobuf.MapField.newMapField(
                  FieldsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000010;
            }
            com.google.protobuf.MapEntry<java.lang.String, io.etrace.proto.metrics.v2.Field>
            fields__ = input.readMessage(
                FieldsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            fields_.getMutableMap().put(
                fields__.getKey(), fields__.getValue());
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) != 0)) {
              buckets_ = new java.util.ArrayList<io.etrace.proto.metrics.v2.Bucket>();
              mutable_bitField0_ |= 0x00000020;
            }
            buckets_.add(
                input.readMessage(io.etrace.proto.metrics.v2.Bucket.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) != 0)) {
        buckets_ = java.util.Collections.unmodifiableList(buckets_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_Metric_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 4:
        return internalGetTags();
      case 5:
        return internalGetFields();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_Metric_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.etrace.proto.metrics.v2.Metric.class, io.etrace.proto.metrics.v2.Metric.Builder.class);
  }

  /**
   * Protobuf enum {@code io.etrace.proto.metrics.v2.Metric.MetricKind}
   */
  public enum MetricKind
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>COUNTER = 0;</code>
     */
    COUNTER(0),
    /**
     * <code>GAUGE = 1;</code>
     */
    GAUGE(1),
    /**
     * <code>TIMER = 2;</code>
     */
    TIMER(2),
    /**
     * <code>RATIO = 3;</code>
     */
    RATIO(3),
    /**
     * <code>PAYLOAD = 4;</code>
     */
    PAYLOAD(4),
    /**
     * <code>HISTOGRAM = 5;</code>
     */
    HISTOGRAM(5),
    /**
     * <code>SUMMARY = 6;</code>
     */
    SUMMARY(6),
    /**
     * <code>HISTOGRAM_INTERNAL = 7;</code>
     */
    HISTOGRAM_INTERNAL(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>COUNTER = 0;</code>
     */
    public static final int COUNTER_VALUE = 0;
    /**
     * <code>GAUGE = 1;</code>
     */
    public static final int GAUGE_VALUE = 1;
    /**
     * <code>TIMER = 2;</code>
     */
    public static final int TIMER_VALUE = 2;
    /**
     * <code>RATIO = 3;</code>
     */
    public static final int RATIO_VALUE = 3;
    /**
     * <code>PAYLOAD = 4;</code>
     */
    public static final int PAYLOAD_VALUE = 4;
    /**
     * <code>HISTOGRAM = 5;</code>
     */
    public static final int HISTOGRAM_VALUE = 5;
    /**
     * <code>SUMMARY = 6;</code>
     */
    public static final int SUMMARY_VALUE = 6;
    /**
     * <code>HISTOGRAM_INTERNAL = 7;</code>
     */
    public static final int HISTOGRAM_INTERNAL_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MetricKind valueOf(int value) {
      return forNumber(value);
    }

    public static MetricKind forNumber(int value) {
      switch (value) {
        case 0: return COUNTER;
        case 1: return GAUGE;
        case 2: return TIMER;
        case 3: return RATIO;
        case 4: return PAYLOAD;
        case 5: return HISTOGRAM;
        case 6: return SUMMARY;
        case 7: return HISTOGRAM_INTERNAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MetricKind>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MetricKind> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MetricKind>() {
            public MetricKind findValueByNumber(int number) {
              return MetricKind.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.etrace.proto.metrics.v2.Metric.getDescriptor().getEnumTypes().get(0);
    }

    private static final MetricKind[] VALUES = values();

    public static MetricKind valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MetricKind(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:io.etrace.proto.metrics.v2.Metric.MetricKind)
  }

  private int bitField0_;
  public static final int KIND_FIELD_NUMBER = 1;
  private int kind_;
  /**
   * <code>.io.etrace.proto.metrics.v2.Metric.MetricKind kind = 1;</code>
   */
  public int getKindValue() {
    return kind_;
  }
  /**
   * <code>.io.etrace.proto.metrics.v2.Metric.MetricKind kind = 1;</code>
   */
  public io.etrace.proto.metrics.v2.Metric.MetricKind getKind() {
    @SuppressWarnings("deprecation")
    io.etrace.proto.metrics.v2.Metric.MetricKind result = io.etrace.proto.metrics.v2.Metric.MetricKind.valueOf(kind_);
    return result == null ? io.etrace.proto.metrics.v2.Metric.MetricKind.UNRECOGNIZED : result;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private long timestamp_;
  /**
   * <code>uint64 timestamp = 3;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int TAGS_FIELD_NUMBER = 4;
  private static final class TagsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_Metric_TagsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> tags_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetTags() {
    if (tags_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          TagsDefaultEntryHolder.defaultEntry);
    }
    return tags_;
  }

  public int getTagsCount() {
    return internalGetTags().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */

  public boolean containsTags(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetTags().getMap().containsKey(key);
  }
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getTags() {
    return getTagsMap();
  }
  /**
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
    return internalGetTags().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */

  public java.lang.String getTagsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTags().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */

  public java.lang.String getTagsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTags().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int FIELDS_FIELD_NUMBER = 5;
  private static final class FieldsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, io.etrace.proto.metrics.v2.Field> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, io.etrace.proto.metrics.v2.Field>newDefaultInstance(
                io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_Metric_FieldsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                io.etrace.proto.metrics.v2.Field.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, io.etrace.proto.metrics.v2.Field> fields_;
  private com.google.protobuf.MapField<java.lang.String, io.etrace.proto.metrics.v2.Field>
  internalGetFields() {
    if (fields_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          FieldsDefaultEntryHolder.defaultEntry);
    }
    return fields_;
  }

  public int getFieldsCount() {
    return internalGetFields().getMap().size();
  }
  /**
   * <code>map&lt;string, .io.etrace.proto.metrics.v2.Field&gt; fields = 5;</code>
   */

  public boolean containsFields(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetFields().getMap().containsKey(key);
  }
  /**
   * Use {@link #getFieldsMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, io.etrace.proto.metrics.v2.Field> getFields() {
    return getFieldsMap();
  }
  /**
   * <code>map&lt;string, .io.etrace.proto.metrics.v2.Field&gt; fields = 5;</code>
   */

  public java.util.Map<java.lang.String, io.etrace.proto.metrics.v2.Field> getFieldsMap() {
    return internalGetFields().getMap();
  }
  /**
   * <code>map&lt;string, .io.etrace.proto.metrics.v2.Field&gt; fields = 5;</code>
   */

  public io.etrace.proto.metrics.v2.Field getFieldsOrDefault(
      java.lang.String key,
      io.etrace.proto.metrics.v2.Field defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, io.etrace.proto.metrics.v2.Field> map =
        internalGetFields().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .io.etrace.proto.metrics.v2.Field&gt; fields = 5;</code>
   */

  public io.etrace.proto.metrics.v2.Field getFieldsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, io.etrace.proto.metrics.v2.Field> map =
        internalGetFields().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int BUCKETS_FIELD_NUMBER = 6;
  private java.util.List<io.etrace.proto.metrics.v2.Bucket> buckets_;
  /**
   * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
   */
  public java.util.List<io.etrace.proto.metrics.v2.Bucket> getBucketsList() {
    return buckets_;
  }
  /**
   * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
   */
  public java.util.List<? extends io.etrace.proto.metrics.v2.BucketOrBuilder> 
      getBucketsOrBuilderList() {
    return buckets_;
  }
  /**
   * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
   */
  public int getBucketsCount() {
    return buckets_.size();
  }
  /**
   * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
   */
  public io.etrace.proto.metrics.v2.Bucket getBuckets(int index) {
    return buckets_.get(index);
  }
  /**
   * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
   */
  public io.etrace.proto.metrics.v2.BucketOrBuilder getBucketsOrBuilder(
      int index) {
    return buckets_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (kind_ != io.etrace.proto.metrics.v2.Metric.MetricKind.COUNTER.getNumber()) {
      output.writeEnum(1, kind_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (timestamp_ != 0L) {
      output.writeUInt64(3, timestamp_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetTags(),
        TagsDefaultEntryHolder.defaultEntry,
        4);
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetFields(),
        FieldsDefaultEntryHolder.defaultEntry,
        5);
    for (int i = 0; i < buckets_.size(); i++) {
      output.writeMessage(6, buckets_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (kind_ != io.etrace.proto.metrics.v2.Metric.MetricKind.COUNTER.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, kind_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, timestamp_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetTags().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      tags__ = TagsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, tags__);
    }
    for (java.util.Map.Entry<java.lang.String, io.etrace.proto.metrics.v2.Field> entry
         : internalGetFields().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, io.etrace.proto.metrics.v2.Field>
      fields__ = FieldsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, fields__);
    }
    for (int i = 0; i < buckets_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, buckets_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.etrace.proto.metrics.v2.Metric)) {
      return super.equals(obj);
    }
    io.etrace.proto.metrics.v2.Metric other = (io.etrace.proto.metrics.v2.Metric) obj;

    if (kind_ != other.kind_) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!internalGetTags().equals(
        other.internalGetTags())) return false;
    if (!internalGetFields().equals(
        other.internalGetFields())) return false;
    if (!getBucketsList()
        .equals(other.getBucketsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KIND_FIELD_NUMBER;
    hash = (53 * hash) + kind_;
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    if (!internalGetTags().getMap().isEmpty()) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetTags().hashCode();
    }
    if (!internalGetFields().getMap().isEmpty()) {
      hash = (37 * hash) + FIELDS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetFields().hashCode();
    }
    if (getBucketsCount() > 0) {
      hash = (37 * hash) + BUCKETS_FIELD_NUMBER;
      hash = (53 * hash) + getBucketsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.etrace.proto.metrics.v2.Metric parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etrace.proto.metrics.v2.Metric parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etrace.proto.metrics.v2.Metric parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etrace.proto.metrics.v2.Metric parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etrace.proto.metrics.v2.Metric parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etrace.proto.metrics.v2.Metric parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etrace.proto.metrics.v2.Metric parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.etrace.proto.metrics.v2.Metric parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.etrace.proto.metrics.v2.Metric parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.etrace.proto.metrics.v2.Metric parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.etrace.proto.metrics.v2.Metric parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.etrace.proto.metrics.v2.Metric parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.etrace.proto.metrics.v2.Metric prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.etrace.proto.metrics.v2.Metric}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.etrace.proto.metrics.v2.Metric)
      io.etrace.proto.metrics.v2.MetricOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_Metric_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetTags();
        case 5:
          return internalGetFields();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetMutableTags();
        case 5:
          return internalGetMutableFields();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_Metric_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.etrace.proto.metrics.v2.Metric.class, io.etrace.proto.metrics.v2.Metric.Builder.class);
    }

    // Construct using io.etrace.proto.metrics.v2.Metric.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBucketsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      kind_ = 0;

      name_ = "";

      timestamp_ = 0L;

      internalGetMutableTags().clear();
      internalGetMutableFields().clear();
      if (bucketsBuilder_ == null) {
        buckets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        bucketsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_Metric_descriptor;
    }

    @java.lang.Override
    public io.etrace.proto.metrics.v2.Metric getDefaultInstanceForType() {
      return io.etrace.proto.metrics.v2.Metric.getDefaultInstance();
    }

    @java.lang.Override
    public io.etrace.proto.metrics.v2.Metric build() {
      io.etrace.proto.metrics.v2.Metric result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.etrace.proto.metrics.v2.Metric buildPartial() {
      io.etrace.proto.metrics.v2.Metric result = new io.etrace.proto.metrics.v2.Metric(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.kind_ = kind_;
      result.name_ = name_;
      result.timestamp_ = timestamp_;
      result.tags_ = internalGetTags();
      result.tags_.makeImmutable();
      result.fields_ = internalGetFields();
      result.fields_.makeImmutable();
      if (bucketsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          buckets_ = java.util.Collections.unmodifiableList(buckets_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.buckets_ = buckets_;
      } else {
        result.buckets_ = bucketsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.etrace.proto.metrics.v2.Metric) {
        return mergeFrom((io.etrace.proto.metrics.v2.Metric)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.etrace.proto.metrics.v2.Metric other) {
      if (other == io.etrace.proto.metrics.v2.Metric.getDefaultInstance()) return this;
      if (other.kind_ != 0) {
        setKindValue(other.getKindValue());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      internalGetMutableTags().mergeFrom(
          other.internalGetTags());
      internalGetMutableFields().mergeFrom(
          other.internalGetFields());
      if (bucketsBuilder_ == null) {
        if (!other.buckets_.isEmpty()) {
          if (buckets_.isEmpty()) {
            buckets_ = other.buckets_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureBucketsIsMutable();
            buckets_.addAll(other.buckets_);
          }
          onChanged();
        }
      } else {
        if (!other.buckets_.isEmpty()) {
          if (bucketsBuilder_.isEmpty()) {
            bucketsBuilder_.dispose();
            bucketsBuilder_ = null;
            buckets_ = other.buckets_;
            bitField0_ = (bitField0_ & ~0x00000020);
            bucketsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBucketsFieldBuilder() : null;
          } else {
            bucketsBuilder_.addAllMessages(other.buckets_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.etrace.proto.metrics.v2.Metric parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.etrace.proto.metrics.v2.Metric) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int kind_ = 0;
    /**
     * <code>.io.etrace.proto.metrics.v2.Metric.MetricKind kind = 1;</code>
     */
    public int getKindValue() {
      return kind_;
    }
    /**
     * <code>.io.etrace.proto.metrics.v2.Metric.MetricKind kind = 1;</code>
     */
    public Builder setKindValue(int value) {
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.io.etrace.proto.metrics.v2.Metric.MetricKind kind = 1;</code>
     */
    public io.etrace.proto.metrics.v2.Metric.MetricKind getKind() {
      @SuppressWarnings("deprecation")
      io.etrace.proto.metrics.v2.Metric.MetricKind result = io.etrace.proto.metrics.v2.Metric.MetricKind.valueOf(kind_);
      return result == null ? io.etrace.proto.metrics.v2.Metric.MetricKind.UNRECOGNIZED : result;
    }
    /**
     * <code>.io.etrace.proto.metrics.v2.Metric.MetricKind kind = 1;</code>
     */
    public Builder setKind(io.etrace.proto.metrics.v2.Metric.MetricKind value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      kind_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.io.etrace.proto.metrics.v2.Metric.MetricKind kind = 1;</code>
     */
    public Builder clearKind() {
      
      kind_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>uint64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>uint64 timestamp = 3;</code>
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 timestamp = 3;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> tags_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetTags() {
      if (tags_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TagsDefaultEntryHolder.defaultEntry);
      }
      return tags_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableTags() {
      onChanged();;
      if (tags_ == null) {
        tags_ = com.google.protobuf.MapField.newMapField(
            TagsDefaultEntryHolder.defaultEntry);
      }
      if (!tags_.isMutable()) {
        tags_ = tags_.copy();
      }
      return tags_;
    }

    public int getTagsCount() {
      return internalGetTags().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 4;</code>
     */

    public boolean containsTags(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetTags().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTagsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getTags() {
      return getTagsMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 4;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
      return internalGetTags().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 4;</code>
     */

    public java.lang.String getTagsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; tags = 4;</code>
     */

    public java.lang.String getTagsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearTags() {
      internalGetMutableTags().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; tags = 4;</code>
     */

    public Builder removeTags(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableTags().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableTags() {
      return internalGetMutableTags().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 4;</code>
     */
    public Builder putTags(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableTags().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; tags = 4;</code>
     */

    public Builder putAllTags(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableTags().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, io.etrace.proto.metrics.v2.Field> fields_;
    private com.google.protobuf.MapField<java.lang.String, io.etrace.proto.metrics.v2.Field>
    internalGetFields() {
      if (fields_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FieldsDefaultEntryHolder.defaultEntry);
      }
      return fields_;
    }
    private com.google.protobuf.MapField<java.lang.String, io.etrace.proto.metrics.v2.Field>
    internalGetMutableFields() {
      onChanged();;
      if (fields_ == null) {
        fields_ = com.google.protobuf.MapField.newMapField(
            FieldsDefaultEntryHolder.defaultEntry);
      }
      if (!fields_.isMutable()) {
        fields_ = fields_.copy();
      }
      return fields_;
    }

    public int getFieldsCount() {
      return internalGetFields().getMap().size();
    }
    /**
     * <code>map&lt;string, .io.etrace.proto.metrics.v2.Field&gt; fields = 5;</code>
     */

    public boolean containsFields(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetFields().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFieldsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.etrace.proto.metrics.v2.Field> getFields() {
      return getFieldsMap();
    }
    /**
     * <code>map&lt;string, .io.etrace.proto.metrics.v2.Field&gt; fields = 5;</code>
     */

    public java.util.Map<java.lang.String, io.etrace.proto.metrics.v2.Field> getFieldsMap() {
      return internalGetFields().getMap();
    }
    /**
     * <code>map&lt;string, .io.etrace.proto.metrics.v2.Field&gt; fields = 5;</code>
     */

    public io.etrace.proto.metrics.v2.Field getFieldsOrDefault(
        java.lang.String key,
        io.etrace.proto.metrics.v2.Field defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, io.etrace.proto.metrics.v2.Field> map =
          internalGetFields().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .io.etrace.proto.metrics.v2.Field&gt; fields = 5;</code>
     */

    public io.etrace.proto.metrics.v2.Field getFieldsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, io.etrace.proto.metrics.v2.Field> map =
          internalGetFields().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearFields() {
      internalGetMutableFields().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .io.etrace.proto.metrics.v2.Field&gt; fields = 5;</code>
     */

    public Builder removeFields(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableFields().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.etrace.proto.metrics.v2.Field>
    getMutableFields() {
      return internalGetMutableFields().getMutableMap();
    }
    /**
     * <code>map&lt;string, .io.etrace.proto.metrics.v2.Field&gt; fields = 5;</code>
     */
    public Builder putFields(
        java.lang.String key,
        io.etrace.proto.metrics.v2.Field value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableFields().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .io.etrace.proto.metrics.v2.Field&gt; fields = 5;</code>
     */

    public Builder putAllFields(
        java.util.Map<java.lang.String, io.etrace.proto.metrics.v2.Field> values) {
      internalGetMutableFields().getMutableMap()
          .putAll(values);
      return this;
    }

    private java.util.List<io.etrace.proto.metrics.v2.Bucket> buckets_ =
      java.util.Collections.emptyList();
    private void ensureBucketsIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        buckets_ = new java.util.ArrayList<io.etrace.proto.metrics.v2.Bucket>(buckets_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.etrace.proto.metrics.v2.Bucket, io.etrace.proto.metrics.v2.Bucket.Builder, io.etrace.proto.metrics.v2.BucketOrBuilder> bucketsBuilder_;

    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
     */
    public java.util.List<io.etrace.proto.metrics.v2.Bucket> getBucketsList() {
      if (bucketsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(buckets_);
      } else {
        return bucketsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
     */
    public int getBucketsCount() {
      if (bucketsBuilder_ == null) {
        return buckets_.size();
      } else {
        return bucketsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
     */
    public io.etrace.proto.metrics.v2.Bucket getBuckets(int index) {
      if (bucketsBuilder_ == null) {
        return buckets_.get(index);
      } else {
        return bucketsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
     */
    public Builder setBuckets(
        int index, io.etrace.proto.metrics.v2.Bucket value) {
      if (bucketsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBucketsIsMutable();
        buckets_.set(index, value);
        onChanged();
      } else {
        bucketsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
     */
    public Builder setBuckets(
        int index, io.etrace.proto.metrics.v2.Bucket.Builder builderForValue) {
      if (bucketsBuilder_ == null) {
        ensureBucketsIsMutable();
        buckets_.set(index, builderForValue.build());
        onChanged();
      } else {
        bucketsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
     */
    public Builder addBuckets(io.etrace.proto.metrics.v2.Bucket value) {
      if (bucketsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBucketsIsMutable();
        buckets_.add(value);
        onChanged();
      } else {
        bucketsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
     */
    public Builder addBuckets(
        int index, io.etrace.proto.metrics.v2.Bucket value) {
      if (bucketsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBucketsIsMutable();
        buckets_.add(index, value);
        onChanged();
      } else {
        bucketsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
     */
    public Builder addBuckets(
        io.etrace.proto.metrics.v2.Bucket.Builder builderForValue) {
      if (bucketsBuilder_ == null) {
        ensureBucketsIsMutable();
        buckets_.add(builderForValue.build());
        onChanged();
      } else {
        bucketsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
     */
    public Builder addBuckets(
        int index, io.etrace.proto.metrics.v2.Bucket.Builder builderForValue) {
      if (bucketsBuilder_ == null) {
        ensureBucketsIsMutable();
        buckets_.add(index, builderForValue.build());
        onChanged();
      } else {
        bucketsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
     */
    public Builder addAllBuckets(
        java.lang.Iterable<? extends io.etrace.proto.metrics.v2.Bucket> values) {
      if (bucketsBuilder_ == null) {
        ensureBucketsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, buckets_);
        onChanged();
      } else {
        bucketsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
     */
    public Builder clearBuckets() {
      if (bucketsBuilder_ == null) {
        buckets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        bucketsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
     */
    public Builder removeBuckets(int index) {
      if (bucketsBuilder_ == null) {
        ensureBucketsIsMutable();
        buckets_.remove(index);
        onChanged();
      } else {
        bucketsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
     */
    public io.etrace.proto.metrics.v2.Bucket.Builder getBucketsBuilder(
        int index) {
      return getBucketsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
     */
    public io.etrace.proto.metrics.v2.BucketOrBuilder getBucketsOrBuilder(
        int index) {
      if (bucketsBuilder_ == null) {
        return buckets_.get(index);  } else {
        return bucketsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
     */
    public java.util.List<? extends io.etrace.proto.metrics.v2.BucketOrBuilder> 
         getBucketsOrBuilderList() {
      if (bucketsBuilder_ != null) {
        return bucketsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(buckets_);
      }
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
     */
    public io.etrace.proto.metrics.v2.Bucket.Builder addBucketsBuilder() {
      return getBucketsFieldBuilder().addBuilder(
          io.etrace.proto.metrics.v2.Bucket.getDefaultInstance());
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
     */
    public io.etrace.proto.metrics.v2.Bucket.Builder addBucketsBuilder(
        int index) {
      return getBucketsFieldBuilder().addBuilder(
          index, io.etrace.proto.metrics.v2.Bucket.getDefaultInstance());
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Bucket buckets = 6;</code>
     */
    public java.util.List<io.etrace.proto.metrics.v2.Bucket.Builder> 
         getBucketsBuilderList() {
      return getBucketsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.etrace.proto.metrics.v2.Bucket, io.etrace.proto.metrics.v2.Bucket.Builder, io.etrace.proto.metrics.v2.BucketOrBuilder> 
        getBucketsFieldBuilder() {
      if (bucketsBuilder_ == null) {
        bucketsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.etrace.proto.metrics.v2.Bucket, io.etrace.proto.metrics.v2.Bucket.Builder, io.etrace.proto.metrics.v2.BucketOrBuilder>(
                buckets_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        buckets_ = null;
      }
      return bucketsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.etrace.proto.metrics.v2.Metric)
  }

  // @@protoc_insertion_point(class_scope:io.etrace.proto.metrics.v2.Metric)
  private static final io.etrace.proto.metrics.v2.Metric DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.etrace.proto.metrics.v2.Metric();
  }

  public static io.etrace.proto.metrics.v2.Metric getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Metric>
      PARSER = new com.google.protobuf.AbstractParser<Metric>() {
    @java.lang.Override
    public Metric parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Metric(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Metric> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Metric> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.etrace.proto.metrics.v2.Metric getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

