// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics/v2/metrics.proto

package io.etrace.proto.metrics.v2;

/**
 * Protobuf type {@code io.etrace.proto.metrics.v2.ResourceMetrics}
 */
public  final class ResourceMetrics extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.etrace.proto.metrics.v2.ResourceMetrics)
    ResourceMetricsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResourceMetrics.newBuilder() to construct.
  private ResourceMetrics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResourceMetrics() {
    metric_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResourceMetrics(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 42: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              attributes_ = com.google.protobuf.MapField.newMapField(
                  AttributesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            attributes__ = input.readMessage(
                AttributesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            attributes_.getMutableMap().put(
                attributes__.getKey(), attributes__.getValue());
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              metric_ = new java.util.ArrayList<io.etrace.proto.metrics.v2.Metric>();
              mutable_bitField0_ |= 0x00000002;
            }
            metric_.add(
                input.readMessage(io.etrace.proto.metrics.v2.Metric.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        metric_ = java.util.Collections.unmodifiableList(metric_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_ResourceMetrics_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 5:
        return internalGetAttributes();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_ResourceMetrics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.etrace.proto.metrics.v2.ResourceMetrics.class, io.etrace.proto.metrics.v2.ResourceMetrics.Builder.class);
  }

  public static final int ATTRIBUTES_FIELD_NUMBER = 5;
  private static final class AttributesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_ResourceMetrics_AttributesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> attributes_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetAttributes() {
    if (attributes_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          AttributesDefaultEntryHolder.defaultEntry);
    }
    return attributes_;
  }

  public int getAttributesCount() {
    return internalGetAttributes().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; attributes = 5;</code>
   */

  public boolean containsAttributes(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetAttributes().getMap().containsKey(key);
  }
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
    return getAttributesMap();
  }
  /**
   * <code>map&lt;string, string&gt; attributes = 5;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
    return internalGetAttributes().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; attributes = 5;</code>
   */

  public java.lang.String getAttributesOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAttributes().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; attributes = 5;</code>
   */

  public java.lang.String getAttributesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAttributes().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int METRIC_FIELD_NUMBER = 6;
  private java.util.List<io.etrace.proto.metrics.v2.Metric> metric_;
  /**
   * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
   */
  public java.util.List<io.etrace.proto.metrics.v2.Metric> getMetricList() {
    return metric_;
  }
  /**
   * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
   */
  public java.util.List<? extends io.etrace.proto.metrics.v2.MetricOrBuilder> 
      getMetricOrBuilderList() {
    return metric_;
  }
  /**
   * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
   */
  public int getMetricCount() {
    return metric_.size();
  }
  /**
   * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
   */
  public io.etrace.proto.metrics.v2.Metric getMetric(int index) {
    return metric_.get(index);
  }
  /**
   * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
   */
  public io.etrace.proto.metrics.v2.MetricOrBuilder getMetricOrBuilder(
      int index) {
    return metric_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetAttributes(),
        AttributesDefaultEntryHolder.defaultEntry,
        5);
    for (int i = 0; i < metric_.size(); i++) {
      output.writeMessage(6, metric_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetAttributes().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      attributes__ = AttributesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, attributes__);
    }
    for (int i = 0; i < metric_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, metric_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.etrace.proto.metrics.v2.ResourceMetrics)) {
      return super.equals(obj);
    }
    io.etrace.proto.metrics.v2.ResourceMetrics other = (io.etrace.proto.metrics.v2.ResourceMetrics) obj;

    if (!internalGetAttributes().equals(
        other.internalGetAttributes())) return false;
    if (!getMetricList()
        .equals(other.getMetricList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetAttributes().getMap().isEmpty()) {
      hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetAttributes().hashCode();
    }
    if (getMetricCount() > 0) {
      hash = (37 * hash) + METRIC_FIELD_NUMBER;
      hash = (53 * hash) + getMetricList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.etrace.proto.metrics.v2.ResourceMetrics parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etrace.proto.metrics.v2.ResourceMetrics parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etrace.proto.metrics.v2.ResourceMetrics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etrace.proto.metrics.v2.ResourceMetrics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etrace.proto.metrics.v2.ResourceMetrics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.etrace.proto.metrics.v2.ResourceMetrics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.etrace.proto.metrics.v2.ResourceMetrics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.etrace.proto.metrics.v2.ResourceMetrics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.etrace.proto.metrics.v2.ResourceMetrics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.etrace.proto.metrics.v2.ResourceMetrics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.etrace.proto.metrics.v2.ResourceMetrics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.etrace.proto.metrics.v2.ResourceMetrics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.etrace.proto.metrics.v2.ResourceMetrics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.etrace.proto.metrics.v2.ResourceMetrics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.etrace.proto.metrics.v2.ResourceMetrics)
      io.etrace.proto.metrics.v2.ResourceMetricsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_ResourceMetrics_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetAttributes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetMutableAttributes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_ResourceMetrics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.etrace.proto.metrics.v2.ResourceMetrics.class, io.etrace.proto.metrics.v2.ResourceMetrics.Builder.class);
    }

    // Construct using io.etrace.proto.metrics.v2.ResourceMetrics.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMetricFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableAttributes().clear();
      if (metricBuilder_ == null) {
        metric_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        metricBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.etrace.proto.metrics.v2.MetricsProto.internal_static_io_etrace_proto_metrics_v2_ResourceMetrics_descriptor;
    }

    @java.lang.Override
    public io.etrace.proto.metrics.v2.ResourceMetrics getDefaultInstanceForType() {
      return io.etrace.proto.metrics.v2.ResourceMetrics.getDefaultInstance();
    }

    @java.lang.Override
    public io.etrace.proto.metrics.v2.ResourceMetrics build() {
      io.etrace.proto.metrics.v2.ResourceMetrics result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.etrace.proto.metrics.v2.ResourceMetrics buildPartial() {
      io.etrace.proto.metrics.v2.ResourceMetrics result = new io.etrace.proto.metrics.v2.ResourceMetrics(this);
      int from_bitField0_ = bitField0_;
      result.attributes_ = internalGetAttributes();
      result.attributes_.makeImmutable();
      if (metricBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          metric_ = java.util.Collections.unmodifiableList(metric_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.metric_ = metric_;
      } else {
        result.metric_ = metricBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.etrace.proto.metrics.v2.ResourceMetrics) {
        return mergeFrom((io.etrace.proto.metrics.v2.ResourceMetrics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.etrace.proto.metrics.v2.ResourceMetrics other) {
      if (other == io.etrace.proto.metrics.v2.ResourceMetrics.getDefaultInstance()) return this;
      internalGetMutableAttributes().mergeFrom(
          other.internalGetAttributes());
      if (metricBuilder_ == null) {
        if (!other.metric_.isEmpty()) {
          if (metric_.isEmpty()) {
            metric_ = other.metric_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMetricIsMutable();
            metric_.addAll(other.metric_);
          }
          onChanged();
        }
      } else {
        if (!other.metric_.isEmpty()) {
          if (metricBuilder_.isEmpty()) {
            metricBuilder_.dispose();
            metricBuilder_ = null;
            metric_ = other.metric_;
            bitField0_ = (bitField0_ & ~0x00000002);
            metricBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMetricFieldBuilder() : null;
          } else {
            metricBuilder_.addAllMessages(other.metric_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.etrace.proto.metrics.v2.ResourceMetrics parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.etrace.proto.metrics.v2.ResourceMetrics) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> attributes_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAttributes() {
      if (attributes_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttributesDefaultEntryHolder.defaultEntry);
      }
      return attributes_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableAttributes() {
      onChanged();;
      if (attributes_ == null) {
        attributes_ = com.google.protobuf.MapField.newMapField(
            AttributesDefaultEntryHolder.defaultEntry);
      }
      if (!attributes_.isMutable()) {
        attributes_ = attributes_.copy();
      }
      return attributes_;
    }

    public int getAttributesCount() {
      return internalGetAttributes().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 5;</code>
     */

    public boolean containsAttributes(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAttributes().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAttributesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
      return getAttributesMap();
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 5;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
      return internalGetAttributes().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 5;</code>
     */

    public java.lang.String getAttributesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttributes().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 5;</code>
     */

    public java.lang.String getAttributesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttributes().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearAttributes() {
      internalGetMutableAttributes().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 5;</code>
     */

    public Builder removeAttributes(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableAttributes().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableAttributes() {
      return internalGetMutableAttributes().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 5;</code>
     */
    public Builder putAttributes(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableAttributes().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 5;</code>
     */

    public Builder putAllAttributes(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableAttributes().getMutableMap()
          .putAll(values);
      return this;
    }

    private java.util.List<io.etrace.proto.metrics.v2.Metric> metric_ =
      java.util.Collections.emptyList();
    private void ensureMetricIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        metric_ = new java.util.ArrayList<io.etrace.proto.metrics.v2.Metric>(metric_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.etrace.proto.metrics.v2.Metric, io.etrace.proto.metrics.v2.Metric.Builder, io.etrace.proto.metrics.v2.MetricOrBuilder> metricBuilder_;

    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
     */
    public java.util.List<io.etrace.proto.metrics.v2.Metric> getMetricList() {
      if (metricBuilder_ == null) {
        return java.util.Collections.unmodifiableList(metric_);
      } else {
        return metricBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
     */
    public int getMetricCount() {
      if (metricBuilder_ == null) {
        return metric_.size();
      } else {
        return metricBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
     */
    public io.etrace.proto.metrics.v2.Metric getMetric(int index) {
      if (metricBuilder_ == null) {
        return metric_.get(index);
      } else {
        return metricBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
     */
    public Builder setMetric(
        int index, io.etrace.proto.metrics.v2.Metric value) {
      if (metricBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricIsMutable();
        metric_.set(index, value);
        onChanged();
      } else {
        metricBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
     */
    public Builder setMetric(
        int index, io.etrace.proto.metrics.v2.Metric.Builder builderForValue) {
      if (metricBuilder_ == null) {
        ensureMetricIsMutable();
        metric_.set(index, builderForValue.build());
        onChanged();
      } else {
        metricBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
     */
    public Builder addMetric(io.etrace.proto.metrics.v2.Metric value) {
      if (metricBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricIsMutable();
        metric_.add(value);
        onChanged();
      } else {
        metricBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
     */
    public Builder addMetric(
        int index, io.etrace.proto.metrics.v2.Metric value) {
      if (metricBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricIsMutable();
        metric_.add(index, value);
        onChanged();
      } else {
        metricBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
     */
    public Builder addMetric(
        io.etrace.proto.metrics.v2.Metric.Builder builderForValue) {
      if (metricBuilder_ == null) {
        ensureMetricIsMutable();
        metric_.add(builderForValue.build());
        onChanged();
      } else {
        metricBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
     */
    public Builder addMetric(
        int index, io.etrace.proto.metrics.v2.Metric.Builder builderForValue) {
      if (metricBuilder_ == null) {
        ensureMetricIsMutable();
        metric_.add(index, builderForValue.build());
        onChanged();
      } else {
        metricBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
     */
    public Builder addAllMetric(
        java.lang.Iterable<? extends io.etrace.proto.metrics.v2.Metric> values) {
      if (metricBuilder_ == null) {
        ensureMetricIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, metric_);
        onChanged();
      } else {
        metricBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
     */
    public Builder clearMetric() {
      if (metricBuilder_ == null) {
        metric_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        metricBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
     */
    public Builder removeMetric(int index) {
      if (metricBuilder_ == null) {
        ensureMetricIsMutable();
        metric_.remove(index);
        onChanged();
      } else {
        metricBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
     */
    public io.etrace.proto.metrics.v2.Metric.Builder getMetricBuilder(
        int index) {
      return getMetricFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
     */
    public io.etrace.proto.metrics.v2.MetricOrBuilder getMetricOrBuilder(
        int index) {
      if (metricBuilder_ == null) {
        return metric_.get(index);  } else {
        return metricBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
     */
    public java.util.List<? extends io.etrace.proto.metrics.v2.MetricOrBuilder> 
         getMetricOrBuilderList() {
      if (metricBuilder_ != null) {
        return metricBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(metric_);
      }
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
     */
    public io.etrace.proto.metrics.v2.Metric.Builder addMetricBuilder() {
      return getMetricFieldBuilder().addBuilder(
          io.etrace.proto.metrics.v2.Metric.getDefaultInstance());
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
     */
    public io.etrace.proto.metrics.v2.Metric.Builder addMetricBuilder(
        int index) {
      return getMetricFieldBuilder().addBuilder(
          index, io.etrace.proto.metrics.v2.Metric.getDefaultInstance());
    }
    /**
     * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
     */
    public java.util.List<io.etrace.proto.metrics.v2.Metric.Builder> 
         getMetricBuilderList() {
      return getMetricFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.etrace.proto.metrics.v2.Metric, io.etrace.proto.metrics.v2.Metric.Builder, io.etrace.proto.metrics.v2.MetricOrBuilder> 
        getMetricFieldBuilder() {
      if (metricBuilder_ == null) {
        metricBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.etrace.proto.metrics.v2.Metric, io.etrace.proto.metrics.v2.Metric.Builder, io.etrace.proto.metrics.v2.MetricOrBuilder>(
                metric_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        metric_ = null;
      }
      return metricBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.etrace.proto.metrics.v2.ResourceMetrics)
  }

  // @@protoc_insertion_point(class_scope:io.etrace.proto.metrics.v2.ResourceMetrics)
  private static final io.etrace.proto.metrics.v2.ResourceMetrics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.etrace.proto.metrics.v2.ResourceMetrics();
  }

  public static io.etrace.proto.metrics.v2.ResourceMetrics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResourceMetrics>
      PARSER = new com.google.protobuf.AbstractParser<ResourceMetrics>() {
    @java.lang.Override
    public ResourceMetrics parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResourceMetrics(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResourceMetrics> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResourceMetrics> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.etrace.proto.metrics.v2.ResourceMetrics getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

