// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics/v2/metrics.proto

package io.etrace.proto.metrics.v2;

public interface ResourceMetricsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.etrace.proto.metrics.v2.ResourceMetrics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; attributes = 5;</code>
   */
  int getAttributesCount();
  /**
   * <code>map&lt;string, string&gt; attributes = 5;</code>
   */
  boolean containsAttributes(
      java.lang.String key);
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getAttributes();
  /**
   * <code>map&lt;string, string&gt; attributes = 5;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAttributesMap();
  /**
   * <code>map&lt;string, string&gt; attributes = 5;</code>
   */

  java.lang.String getAttributesOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; attributes = 5;</code>
   */

  java.lang.String getAttributesOrThrow(
      java.lang.String key);

  /**
   * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
   */
  java.util.List<io.etrace.proto.metrics.v2.Metric> 
      getMetricList();
  /**
   * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
   */
  io.etrace.proto.metrics.v2.Metric getMetric(int index);
  /**
   * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
   */
  int getMetricCount();
  /**
   * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
   */
  java.util.List<? extends io.etrace.proto.metrics.v2.MetricOrBuilder> 
      getMetricOrBuilderList();
  /**
   * <code>repeated .io.etrace.proto.metrics.v2.Metric metric = 6;</code>
   */
  io.etrace.proto.metrics.v2.MetricOrBuilder getMetricOrBuilder(
      int index);
}
