// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trace/v2/trace.proto

package io.etrace.proto.trace.v2;

public interface SpanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.etrace.proto.trace.v2.Span)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string status = 3;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 3;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>uint64 id = 4;</code>
   */
  long getId();

  /**
   * <code>uint64 timestamp = 5;</code>
   */
  long getTimestamp();

  /**
   * <code>bool completed = 6;</code>
   */
  boolean getCompleted();

  /**
   * <code>.io.etrace.proto.trace.v2.SpanKind kind = 7;</code>
   */
  int getKindValue();
  /**
   * <code>.io.etrace.proto.trace.v2.SpanKind kind = 7;</code>
   */
  io.etrace.proto.trace.v2.SpanKind getKind();

  /**
   * <code>map&lt;string, string&gt; tags = 8;</code>
   */
  int getTagsCount();
  /**
   * <code>map&lt;string, string&gt; tags = 8;</code>
   */
  boolean containsTags(
      java.lang.String key);
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getTags();
  /**
   * <code>map&lt;string, string&gt; tags = 8;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getTagsMap();
  /**
   * <code>map&lt;string, string&gt; tags = 8;</code>
   */

  java.lang.String getTagsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; tags = 8;</code>
   */

  java.lang.String getTagsOrThrow(
      java.lang.String key);

  /**
   * <code>string data = 9;</code>
   */
  java.lang.String getData();
  /**
   * <code>string data = 9;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();

  /**
   * <code>uint64 duration = 10;</code>
   */
  long getDuration();

  /**
   * <code>repeated .io.etrace.proto.trace.v2.Span children = 11;</code>
   */
  java.util.List<io.etrace.proto.trace.v2.Span> 
      getChildrenList();
  /**
   * <code>repeated .io.etrace.proto.trace.v2.Span children = 11;</code>
   */
  io.etrace.proto.trace.v2.Span getChildren(int index);
  /**
   * <code>repeated .io.etrace.proto.trace.v2.Span children = 11;</code>
   */
  int getChildrenCount();
  /**
   * <code>repeated .io.etrace.proto.trace.v2.Span children = 11;</code>
   */
  java.util.List<? extends io.etrace.proto.trace.v2.SpanOrBuilder> 
      getChildrenOrBuilderList();
  /**
   * <code>repeated .io.etrace.proto.trace.v2.Span children = 11;</code>
   */
  io.etrace.proto.trace.v2.SpanOrBuilder getChildrenOrBuilder(
      int index);
}
