// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trace/v2/trace.proto

package io.etrace.proto.trace.v2;

public final class TraceProto {
  private TraceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_etrace_proto_trace_v2_Trace_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_etrace_proto_trace_v2_Trace_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_etrace_proto_trace_v2_Trace_AttributesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_etrace_proto_trace_v2_Trace_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_etrace_proto_trace_v2_Span_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_etrace_proto_trace_v2_Span_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_etrace_proto_trace_v2_Span_TagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_etrace_proto_trace_v2_Span_TagsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024trace/v2/trace.proto\022\030io.etrace.proto." +
      "trace.v2\"\321\001\n\005Trace\022\022\n\nrequest_id\030\001 \001(\t\022\016" +
      "\n\006rpc_id\030\002 \001(\t\022C\n\nattributes\030\003 \003(\0132/.io." +
      "etrace.proto.trace.v2.Trace.AttributesEn" +
      "try\022,\n\004span\030\004 \001(\0132\036.io.etrace.proto.trac" +
      "e.v2.Span\0321\n\017AttributesEntry\022\013\n\003key\030\001 \001(" +
      "\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\315\002\n\004Span\022\014\n\004type\030\001 " +
      "\001(\t\022\014\n\004name\030\002 \001(\t\022\016\n\006status\030\003 \001(\t\022\n\n\002id\030" +
      "\004 \001(\004\022\021\n\ttimestamp\030\005 \001(\004\022\021\n\tcompleted\030\006 " +
      "\001(\010\0220\n\004kind\030\007 \001(\0162\".io.etrace.proto.trac" +
      "e.v2.SpanKind\0226\n\004tags\030\010 \003(\0132(.io.etrace." +
      "proto.trace.v2.Span.TagsEntry\022\014\n\004data\030\t " +
      "\001(\t\022\020\n\010duration\030\n \001(\004\0220\n\010children\030\013 \003(\0132" +
      "\036.io.etrace.proto.trace.v2.Span\032+\n\tTagsE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001*d\n\010" +
      "SpanKind\022\t\n\005LOCAL\020\000\022\t\n\005EVENT\020\001\022\n\n\006SERVER" +
      "\020\002\022\n\n\006CLIENT\020\003\022\007\n\003DAL\020\004\022\007\n\003RMQ\020\005\022\t\n\005REDI" +
      "S\020\006\022\r\n\tHEARTBEAT\020\007B(\n\030io.etrace.proto.tr" +
      "ace.v2B\nTraceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_io_etrace_proto_trace_v2_Trace_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_etrace_proto_trace_v2_Trace_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_etrace_proto_trace_v2_Trace_descriptor,
        new java.lang.String[] { "RequestId", "RpcId", "Attributes", "Span", });
    internal_static_io_etrace_proto_trace_v2_Trace_AttributesEntry_descriptor =
      internal_static_io_etrace_proto_trace_v2_Trace_descriptor.getNestedTypes().get(0);
    internal_static_io_etrace_proto_trace_v2_Trace_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_etrace_proto_trace_v2_Trace_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_io_etrace_proto_trace_v2_Span_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_etrace_proto_trace_v2_Span_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_etrace_proto_trace_v2_Span_descriptor,
        new java.lang.String[] { "Type", "Name", "Status", "Id", "Timestamp", "Completed", "Kind", "Tags", "Data", "Duration", "Children", });
    internal_static_io_etrace_proto_trace_v2_Span_TagsEntry_descriptor =
      internal_static_io_etrace_proto_trace_v2_Span_descriptor.getNestedTypes().get(0);
    internal_static_io_etrace_proto_trace_v2_Span_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_etrace_proto_trace_v2_Span_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
