// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector/metrics/v2/metrics_service.proto

package io.etrace.proto.collector.metrics.v2;

public interface MetricsServiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.etrace.proto.collector.metrics.v2.MetricsServiceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes result = 1;</code>
   */
  com.google.protobuf.ByteString getResult();
}
