// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector/metrics/v2/metrics_service.proto

package io.etrace.proto.collector.metrics.v2;

public interface MetricsServiceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.etrace.proto.collector.metrics.v2.MetricsServiceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.etrace.proto.common.v2.Resource resource = 1;</code>
   */
  boolean hasResource();
  /**
   * <code>.io.etrace.proto.common.v2.Resource resource = 1;</code>
   */
  io.etrace.proto.common.v2.Resource getResource();
  /**
   * <code>.io.etrace.proto.common.v2.Resource resource = 1;</code>
   */
  io.etrace.proto.common.v2.ResourceOrBuilder getResourceOrBuilder();

  /**
   * <code>.io.etrace.proto.metrics.v2.ResourceMetrics resource_metrics = 2;</code>
   */
  boolean hasResourceMetrics();
  /**
   * <code>.io.etrace.proto.metrics.v2.ResourceMetrics resource_metrics = 2;</code>
   */
  io.etrace.proto.metrics.v2.ResourceMetrics getResourceMetrics();
  /**
   * <code>.io.etrace.proto.metrics.v2.ResourceMetrics resource_metrics = 2;</code>
   */
  io.etrace.proto.metrics.v2.ResourceMetricsOrBuilder getResourceMetricsOrBuilder();
}
