// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector/metrics/v2/metrics_service.proto

package io.etrace.proto.collector.metrics.v2;

public final class MetricsServiceProto {
  private MetricsServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_etrace_proto_collector_metrics_v2_MetricsServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_etrace_proto_collector_metrics_v2_MetricsServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_etrace_proto_collector_metrics_v2_MetricsServiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_etrace_proto_collector_metrics_v2_MetricsServiceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*collector/metrics/v2/metrics_service.p" +
      "roto\022$io.etrace.proto.collector.metrics." +
      "v2\032\030metrics/v2/metrics.proto\032\030common/v2/" +
      "resource.proto\"\225\001\n\025MetricsServiceRequest" +
      "\0225\n\010resource\030\001 \001(\0132#.io.etrace.proto.com" +
      "mon.v2.Resource\022E\n\020resource_metrics\030\002 \001(" +
      "\0132+.io.etrace.proto.metrics.v2.ResourceM" +
      "etrics\"(\n\026MetricsServiceResponse\022\016\n\006resu" +
      "lt\030\001 \001(\0142\226\001\n\016MetricsService\022\203\001\n\004Send\022;.i" +
      "o.etrace.proto.collector.metrics.v2.Metr" +
      "icsServiceRequest\032<.io.etrace.proto.coll" +
      "ector.metrics.v2.MetricsServiceResponse\"" +
      "\000B=\n$io.etrace.proto.collector.metrics.v" +
      "2B\023MetricsServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.etrace.proto.metrics.v2.MetricsProto.getDescriptor(),
          io.etrace.proto.common.v2.ResourceProto.getDescriptor(),
        }, assigner);
    internal_static_io_etrace_proto_collector_metrics_v2_MetricsServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_etrace_proto_collector_metrics_v2_MetricsServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_etrace_proto_collector_metrics_v2_MetricsServiceRequest_descriptor,
        new java.lang.String[] { "Resource", "ResourceMetrics", });
    internal_static_io_etrace_proto_collector_metrics_v2_MetricsServiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_etrace_proto_collector_metrics_v2_MetricsServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_etrace_proto_collector_metrics_v2_MetricsServiceResponse_descriptor,
        new java.lang.String[] { "Result", });
    io.etrace.proto.metrics.v2.MetricsProto.getDescriptor();
    io.etrace.proto.common.v2.ResourceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
